In [1]:
import os, json 
from pandas import Series

with open("legend.json", "r") as f:
    legend = json.load(f)

with open("labels.json", "r") as f:
    labels = json.load(f)

In [2]:
total_number_of_label_groups = len(legend)
total_number_of_labels = 0
reverse_labels = {}
for group in legend:
  total_number_of_labels += len(legend[group])
  reverse_labels |= {label: key for key, label in legend[group].items()}

print("Total number of label groups:", total_number_of_label_groups)
print("Total number of distinct labels:", total_number_of_labels)

Total number of label groups: 26
Total number of distinct labels: 245

In [3]:
label_distribution = Series(labels).value_counts().reset_index().rename(columns={"index": "label"})
label_distribution["label_name"] = label_distribution["label"].map(reverse_labels)

label_distribution[:60]

    label  count       label_name
0     ca0   9710              dog
1     re0   4258            snake
2     eq0   4100            horse
3     ve0   3323              car
4     tr0   3172            train
5    pri0   2753           monkey
6     ai0   2633  passenger plane
7     re3   2567           lizard
8     bi0   2445             bird
9     ru2   1655           cattle
10    ai3   1536   military plane
11    ru0   1448             deer
12    cy2   1351          bicycle
13    ru3   1341            sheep
14    wa6   1339       other boat
15    ro5   1215           rabbit
16   wa10   1119       cargo ship
17    fe0   1104              cat
18    an0   1072         antelope
19    ai1   1012      small plane
20    ve7    972              van
21    wa0    966      wooden boat
22    re1    960           turtle
23    ve4    932              bus
24   car0    929   horse carriage
25    wa7    898        sail ship
26    pr0    883          raccoon
27    cy0    877       motorcycle
28   tru2    811    freight truck
29   wa11    809       other ship
30    ro4    794         squirrel
31    ai6    734  hot air balloon
32    ai2    708        sea plane
33   car5    700   other carriage
34    ca1    670              fox
35    re2    634       sea turtle
36   mac6    624           rocket
37    mm1    621            whale
38    ro0    608            mouse
39    wa5    606        sail boat
40  pri10    588              ape
41   pri2    560            lemur
42    ai5    559       helicopter
43    ru4    548             goat
44    re5    546   monitor lizard
45    wa8    529      cruise ship
46    om1    506         elephant
47    ai7    491         zeppelin
48   tru9    487        firetruck
49    wa2    461   catamaran boat
50    ro1    451              rat
51   pri4    445          gorilla
52   tru4    437  small-box truck
53    an2    382             oryx
54    wa9    371    military ship
55    eq1    370           donkey
56    fe3    363          leopard
57    ut3    362   buffet trolley
58    ut0    361    shopping cart
59   tru6    358     pickup truck